### ISSUE TITLE
Wrong Blessing of Might/Wisdom Spell ID

### ISSUE THREAD

**Issue by tywtyw2002** [psynct/PowerRaid#1]
The current Spell ID for BoM/BoW is the following content. However, the spell id 25782(BoM) and 25894(BoW) are missing.

```
PowerRaidData.PaladinBuffs["Greater Blessing of Might"] = {
    ["alts"] = {"25916", "25291"},

PowerRaidData.PaladinBuffs["Greater Blessing of Wisdom"] = {
["alts"] = {"25918", "25290"},
```

**Comment by psynct** [comment]
Fixed in [v3.2.4](https://github.com/psynct/PowerRaid/releases/tag/v3.2.4), thanks for reporting this issue!
